openapi: 3.0.0
info:
  description: API for BlockScout web app
  version: 1.0.0
  title: BlockScout Addresses Transactions API
  contact:
    email: support@blockscout.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://eth.blockscout.com/api/v2/
  description: Ethereum mainnet
- url: https://optimism.blockscout.com/api/v2/
  description: Optimism mainnet
- url: https://base.blockscout.com/api/v2/
  description: Base mainnet
- url: https://eth-sepolia.blockscout.com/api/v2/
  description: Ethereum testnet
tags:
- name: Transactions
paths:
  /transactions:
    get:
      parameters:
      - in: query
        name: filter
        schema:
          type: string
          example: pending | validated
      - in: query
        name: type
        schema:
          type: string
          example: token_transfer,contract_creation,contract_call,coin_transfer,token_creation
      - in: query
        name: method
        schema:
          type: string
          example: approve,transfer,multicall,mint,commit
      summary: get transactions
      operationId: get_txs
      responses:
        '200':
          description: block
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  next_page_params:
                    type: object
                    example:
                      block_number: 27170298
                      index: 0
                      items_count: 50
        '400':
          description: bad input parameter
      tags:
      - Transactions
  /transactions/{transaction_hash}:
    get:
      summary: get transaction info
      operationId: get_tx
      parameters:
      - $ref: '#/components/parameters/transactionHash'
      responses:
        '200':
          description: transaction info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: bad input parameter
      tags:
      - Transactions
  /transactions/{transaction_hash}/token-transfers:
    get:
      summary: get transaction token transfers
      operationId: get_transaction_token_transfers
      parameters:
      - $ref: '#/components/parameters/transactionHash'
      - in: query
        name: type
        schema:
          type: string
          example: ERC-20,ERC-721,ERC-1155
      responses:
        '200':
          description: token transfers
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/TokenTransfer'
                  next_page_params:
                    type: object
                    example:
                      block_number: 27350206
                      index: 1
                      items_count: 50
                      transaction_hash: '0xa3b401d6f3124c9d1528cd8d4b692f523d86fd88e48c391ffe9c67e4436ae5ca'
              examples:
                large_1155_batch:
                  $ref: '#/components/examples/TokenTransferLarge1155Batch'
                some_batches_on_the_first_page_and_one_on_the_second:
                  $ref: '#/components/examples/TokenTransferSomeBatchesOnTheFirstPageAndOneOnTheSecond'
                a_lot_of_batches:
                  $ref: '#/components/examples/TokenTransferALotOfBatches'
        '400':
          description: bad input parameter
      tags:
      - Transactions
  /transactions/{transaction_hash}/internal-transactions:
    get:
      summary: get transaction internal transactions
      operationId: get_transaction_internal_txs
      parameters:
      - $ref: '#/components/parameters/transactionHash'
      responses:
        '200':
          description: internal transactions
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/InternalTransaction'
                  next_page_params:
                    type: object
                    example:
                      block_number: 27350206
                      index: 1
                      items_count: 50
                      transaction_index: 0
        '400':
          description: bad input parameter
      tags:
      - Transactions
  /transactions/{transaction_hash}/logs:
    get:
      summary: get transaction logs
      operationId: get_transaction_logs
      parameters:
      - $ref: '#/components/parameters/transactionHash'
      responses:
        '200':
          description: internal transactions
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Log'
                  next_page_params:
                    type: object
                    example:
                      index: 0
                      items_count: 50
                      block_number: 2
        '400':
          description: bad input parameter
      tags:
      - Transactions
  /transactions/{transaction_hash}/raw-trace:
    get:
      summary: get transaction raw trace
      operationId: get_transaction_raw_trace
      parameters:
      - $ref: '#/components/parameters/transactionHash'
      responses:
        '200':
          description: raw trace
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RawTrace'
        '400':
          description: bad input parameter
      tags:
      - Transactions
  /transactions/{transaction_hash}/state-changes:
    get:
      summary: get transaction state changes
      operationId: get_transaction_state_changes
      parameters:
      - $ref: '#/components/parameters/transactionHash'
      responses:
        '200':
          description: state changes
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/StateChange'
                  next_page_params:
                    type: object
                    example:
                      items_count: 1
                      state_changes: null
        '400':
          description: bad input parameter
      tags:
      - Transactions
  /transactions/{transaction_hash}/summary:
    get:
      summary: get human-readable transaction summary
      operationId: get_transaction_summary
      parameters:
      - $ref: '#/components/parameters/transactionHash'
      responses:
        '200':
          description: human-readable transaction summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionSummary'
        '400':
          description: bad input parameter
      tags:
      - Transactions
components:
  examples:
    TokenTransferLarge1155Batch:
      value:
        items:
        - block_hash: '0xf569ec751152b2f814001fc730f7797aa155e4bc3ba9cb6ba24bc2c8c9468c1a'
          from:
            hash: '0xcc4e74EB7F0D2F3e8c86Ac08A6B70689F564b226'
            implementation_name: null
            is_contract: false
            is_verified: false
            name: null
            private_tags: []
            public_tags: []
            watchlist_names: []
          log_index: '243'
          method: null
          timestamp: null
          to:
            hash: '0xEf8801eaf234ff82801821FFe2d78D60a0237F97'
            implementation_name: null
            is_contract: false
            is_verified: false
            name: null
            private_tags: []
            public_tags: []
            watchlist_names: []
          token:
            address_hash: '0xdAC17F958D2ee523a2206206994597C13D831ec7'
            circulating_market_cap: '83606435600.3635'
            decimals: '6'
            exchange_rate: '0.999487'
            holders_count: '1149'
            icon_url: null
            name: Tether USD
            symbol: USDT
            total_supply: '39030615894320966'
            type: ERC-20
          total:
            decimals: '6'
            value: '830000000'
          transaction_hash: '0x6662ad1ad2ea899e9e27832dc202fd2ef915a5d2816c1142e6933cff93f7c592'
          type: token_transfer
        next_page_params:
          batch_block_hash: '0x0000000000000000000000000000000000000000000000000000000000000000'
          batch_log_index: 0
          batch_transaction_hash: '0x0000000000000000000000000000000000000000000000000000000000000000'
          index_in_batch: 1
    TokenTransferSomeBatchesOnTheFirstPageAndOneOnTheSecond:
      value:
        items:
        - block_hash: '0xf569ec751152b2f814001fc730f7797aa155e4bc3ba9cb6ba24bc2c8c9468c1a'
          from:
            hash: '0xcc4e74EB7F0D2F3e8c86Ac08A6B70689F564b226'
            implementation_name: null
            is_contract: false
            is_verified: false
            name: null
            private_tags: []
            public_tags: []
            watchlist_names: []
          log_index: '243'
          method: null
          timestamp: null
          to:
            hash: '0xEf8801eaf234ff82801821FFe2d78D60a0237F97'
            implementation_name: null
            is_contract: false
            is_verified: false
            name: null
            private_tags: []
            public_tags: []
            watchlist_names: []
          token:
            address_hash: '0xdAC17F958D2ee523a2206206994597C13D831ec7'
            circulating_market_cap: '83606435600.3635'
            decimals: '6'
            exchange_rate: '0.999487'
            holders_count: '1149'
            icon_url: null
            name: Tether USD
            symbol: USDT
            total_supply: '39030615894320966'
            type: ERC-20
          total:
            decimals: '6'
            value: '830000000'
          transaction_hash: '0x6662ad1ad2ea899e9e27832dc202fd2ef915a5d2816c1142e6933cff93f7c592'
          type: token_transfer
        next_page_params:
          block_number: 4
          index: 2
    TokenTransferALotOfBatches:
      value:
        items:
        - block_hash: '0xf569ec751152b2f814001fc730f7797aa155e4bc3ba9cb6ba24bc2c8c9468c1a'
          from:
            hash: '0xcc4e74EB7F0D2F3e8c86Ac08A6B70689F564b226'
            implementation_name: null
            is_contract: false
            is_verified: false
            name: null
            private_tags: []
            public_tags: []
            watchlist_names: []
          log_index: '243'
          method: null
          timestamp: null
          to:
            hash: '0xEf8801eaf234ff82801821FFe2d78D60a0237F97'
            implementation_name: null
            is_contract: false
            is_verified: false
            name: null
            private_tags: []
            public_tags: []
            watchlist_names: []
          token:
            address_hash: '0xdAC17F958D2ee523a2206206994597C13D831ec7'
            circulating_market_cap: '83606435600.3635'
            decimals: '6'
            exchange_rate: '0.999487'
            holders_count: '1149'
            icon_url: null
            name: Tether USD
            symbol: USDT
            total_supply: '39030615894320966'
            type: ERC-20
          total:
            decimals: '6'
            value: '830000000'
          transaction_hash: '0x6662ad1ad2ea899e9e27832dc202fd2ef915a5d2816c1142e6933cff93f7c592'
          type: token_transfer
        next_page_params:
          batch_block_hash: '0x0000000000000000000000000000000000000000000000000000000000000014'
          batch_log_index: 5
          batch_transaction_hash: '0x000000000000000000000000000000000000000000000000000000000000000a'
          block_number: 14
          index: 4
          index_in_batch: 1
  schemas:
    TotalERC20:
      required:
      - decimals
      - value
      properties:
        decimals:
          type: string
          example: '18'
        value:
          type: string
          example: '1000'
    DecodedInput:
      type: object
      required:
      - method_call
      - method_id
      - parameters
      properties:
        method_call:
          type: string
          example: transferFrom(address _from, address _to, uint256 _value)
        method_id:
          type: string
          example: 23b872dd
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/DecodedInputParameter'
    TransactionSummary:
      type: object
      required:
      - success
      - data
      properties:
        success:
          type: boolean
          example: true
        data:
          $ref: '#/components/schemas/TransactionSummaryObj'
    DecodedInputLog:
      type: object
      required:
      - method_call
      - method_id
      - parameters
      properties:
        method_call:
          type: string
          example: transferFrom(address _from, address _to, uint256 _value)
        method_id:
          type: string
          example: 23b872dd
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/DecodedInputLogParameter'
    Transaction:
      type: object
      required:
      - timestamp
      - fee
      - gas_limit
      - block_number
      - status
      - method
      - confirmations
      - type
      - exchange_rate
      - to
      - transaction_burnt_fee
      - max_fee_per_gas
      - result
      - hash
      - gas_price
      - priority_fee
      - base_fee_per_gas
      - from
      - token_transfers
      - transaction_types
      - gas_used
      - created_contract
      - position
      - nonce
      - has_error_in_internal_transactions
      - actions
      - decoded_input
      - token_transfers_overflow
      - raw_input
      - value
      - max_priority_fee_per_gas
      - revert_reason
      - confirmation_duration
      - transaction_tag
      properties:
        timestamp:
          type: string
          example: '2022-08-02T07:18:05.000000Z'
        fee:
          $ref: '#/components/schemas/Fee'
        gas_limit:
          type: integer
        block_number:
          type: integer
          format: int32
          example: 23484035
        status:
          type: string
          example: ok | error
        method:
          type: string
          example: transferFrom
        confirmations:
          type: integer
          example: 1035
        type:
          type: integer
          example: 2
        exchange_rate:
          type: string
          example: '1866.51'
        to:
          nullable: true,
          $ref: '#/components/schemas/AddressParam'
        transaction_burnt_fee:
          type: string
          example: '1099596081903840'
        max_fee_per_gas:
          type: string
          example: '55357460102'
        result:
          type: string
          example: 'Error: (Awaiting internal transactions for reason)'
        hash:
          type: string
          example: '0x5d90a9da2b8da402b11bc92c8011ec8a62a2d59da5c7ac4ae0f73ec51bb73368'
        gas_price:
          type: string
          example: '26668595172'
        priority_fee:
          type: string
          example: '2056916056308'
        base_fee_per_gas:
          type: string
          example: '26618801760'
        from:
          $ref: '#/components/schemas/AddressParam'
        token_transfers:
          type: array
          items:
            $ref: '#/components/schemas/TokenTransfer'
        transaction_types:
          type: array
          items:
            type: string
          example:
          - token_transfer
          - contract_creation
          - contract_call
          - token_creation
          - coin_transfer
        gas_used:
          type: string
          example: '41309'
        created_contract:
          nullable: true,
          $ref: '#/components/schemas/AddressParam'
        position:
          type: integer
          example: 117
        nonce:
          type: integer
          example: 115
        has_error_in_internal_transactions:
          type: boolean
          example: false
        actions:
          type: array
          items:
            $ref: '#/components/schemas/TransactionAction'
        decoded_input:
          $ref: '#/components/schemas/DecodedInput'
        token_transfers_overflow:
          type: boolean
          example: false
        raw_input:
          type: string
          example: '0xa9059cbb000000000000000000000000ef8801eaf234ff82801821ffe2d78d60a0237f97000000000000000000000000000000000000000000000000000000003178cb80'
        value:
          type: string
          example: '0'
        max_priority_fee_per_gas:
          type: string
          example: '49793412'
        revert_reason:
          type: string
          example: 'Error: (Awaiting internal transactions for reason)'
        confirmation_duration:
          type: object
          example:
          - 0
          - 17479.0
        transaction_tag:
          type: string
          example: private_transaction_tag
    SummaryVariableCurrency:
      type: object
      required:
      - type
      - value
      properties:
        type:
          type: string
          example: currency
          description: Currency type
        value:
          type: string
          example: '0.195999999980484004'
          description: Value
    TransactionActionUniswapV3MintNFT:
      required:
      - data
      - protocol
      - type
      properties:
        data:
          type: object
          example:
            name: 'Uniswap V3: Positions NFT'
            symbol: UNI-V3-POS
            address: '0x1F98431c8aD98523631AE4a59f267346ea31F984'
            to: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9'
            ids:
            - '1'
            - '2'
            block_number: 1
        protocol:
          type: string
          example: uniswap_v3
        type:
          type: string
          example: mint_nft
    RawTraceCreateAction:
      type: object
      required:
      - from
      - gas
      - init
      - value
      properties:
        from:
          type: string
          example: '0xf57b55b01b831e602e09674a4e5d69cbcf343f98'
        gas:
          type: string
          example: '0x25D3FC'
        init:
          type: string
          example: '0x630cea8e000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000041c25b36779231e71769118210c3eb64c0a9c7577b925b309af3183e13acc7cf30210493d13c8c6c3c0bd337d5e39e454fece0c301f0aedb6c43c7a37650ac83e71c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000019500050000f0add9e5dc02faeca12e9669f045685449d6b80a000000000000744359447362798334d3485c64d1e4870fde2ddc0d75f0b456250dc9990662a6f25808cc74a6d1131ea9000927c001018064382ae87cdd000000000000000000000000bab3cbdcbcc578445480a79ed80269c50bb5b71800000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000012000000000000000000000000351af1631aa5ea1ca62ad8a4e3cd87128d4d910800000000000000000000000000000000000000000000005b8decde02914ce837000000000000000000000000000000000000000000000000000000000000001e4d45444f4f5a412045636f73797374656d2076322e30206f6e2078446169000000000000000000000000000000000000000000000000000000000000000000044d445a41000000000000000000000000000000000000000000000000000000000000000000000000000000'
        value:
          type: string
          example: '0x0'
    RawTraceCreateResult:
      type: object
      required:
      - address
      - code
      - gasUsed
      properties:
        address:
          type: string
          example: '0xf57b55b01b831e602e09674a4e5d69cbcf343f98'
        code:
          type: string
          example: '0x25D3FC'
        gasUsed:
          type: string
          example: '0x25D3FC'
    InternalTransaction:
      type: object
      required:
      - block_number
      - created_contract
      - error
      - from
      - gas_limit
      - index
      - success
      - timestamp
      - to
      - transaction_hash
      - type
      - value
      properties:
        block_number:
          type: integer
          example: 8844586
        created_contract:
          $ref: '#/components/schemas/AddressParam'
        error:
          type: string
          example: reverted
        from:
          $ref: '#/components/schemas/AddressParam'
        gas_limit:
          type: string
          example: '351759'
        index:
          type: integer
          example: 1
        success:
          type: boolean
          example: true
        timestamp:
          type: string
          example: '2023-04-17T10:37:12.000000Z'
        to:
          $ref: '#/components/schemas/AddressParam'
        transaction_hash:
          type: string
          example: '0x08ea4d75ad0abe327a7fd368733eaeac43077989e635d800530d7906ebf3bd54'
        type:
          type: string
          example: call
        value:
          type: string
          example: '30000000000000000'
    RawTraceSelfDestructAction:
      type: object
      required:
      - address
      - balance
      - refundAddress
      properties:
        address:
          type: string
          example: '0xf57b55b01b831e602e09674a4e5d69cbcf343f98'
        balance:
          type: string
          example: '0x25D3FC'
        refundAddress:
          type: string
          example: '0x162e898bd0aacb578c8d5f8d6ca588c13d2a383f'
    Summary:
      type: object
      required:
      - summary_template
      - summary_template_variables
      properties:
        summary_template:
          type: string
          example: '{action_type} of {amount} {token}'
          description: Summary template
        summary_template_variables:
          $ref: '#/components/schemas/SummaryTemplateVariables'
          description: Variables for summary
    NFTChange:
      required:
      - direction
      - total
      properties:
        direction:
          type: string
          example: from | to
        total:
          $ref: '#/components/schemas/TotalERC721'
    TotalERC1155:
      required:
      - token_id
      - decimals
      - value
      properties:
        token_id:
          type: string
          example: '1'
        decimals:
          type: string
          example: null
        value:
          type: string
          example: '1000'
        token_instance:
          $ref: '#/components/schemas/NFTInstance'
    TransactionActionAaveV3BSWRF:
      required:
      - data
      - protocol
      - type
      properties:
        data:
          type: object
          example:
            amount: '1.289548595490270429'
            symbol: AAVE
            address: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9'
            block_number: 1
        protocol:
          type: string
          example: aave_v3
        type:
          type: string
          example: borrow | supply | withdraw | repay | flash_loan
    TokenInfoDetailed:
      type: object
      required:
      - address
      - circulating_market_cap
      - decimals
      - exchange_rate
      - holders
      - icon_url
      - name
      - symbol
      - total_supply
      - type
      - volume_24h
      properties:
        address_hash:
          type: string
          example: '0xBEEF69Ac7870777598A04B2bd4771c71212E6aBc'
          description: Token Address
        circulating_market_cap:
          type: string
          example: '0.0'
          description: Token circulating market cap
        decimals:
          type: string
          example: '18'
          description: Token decimals
        exchange_rate:
          type: string
          example: '2890.96'
          description: Token exchange rate
        holders_count:
          type: string
          example: '2999'
          description: Token holders amount
        icon_url:
          type: string
          example: https://assets.coingecko.com/coins/images/39410/small/Steakhouse_logo-05.jpg?1722053893
          description: 'Token image URL '
        name:
          type: string
          example: Steakhouse Resteaking Vault
          description: Token name
        symbol:
          type: string
          example: steakLRT
          description: Token symbol
        total_supply:
          type: string
          example: '9710057205959239302188'
          description: Token total supply
        type:
          type: string
          example: ERC-20
          description: Token type
        volume_24h:
          type: string
          example: '24298.765344836862'
          description: Token trading volume for past 24h
    TokenTransfer:
      type: object
      required:
      - block_hash
      - from
      - log_index
      - to
      - token
      - total
      - transaction_hash
      - type
      properties:
        block_hash:
          type: string
          example: '0xf569ec751152b2f814001fc730f7797aa155e4bc3ba9cb6ba24bc2c8c9468c1a'
        from:
          $ref: '#/components/schemas/AddressParam'
        log_index:
          type: integer
          example: 16
        method:
          type: string
          example: transfer
        timestamp:
          type: string
          example: '2023-07-03T20:09:59.000000Z'
        to:
          $ref: '#/components/schemas/AddressParam'
        token:
          $ref: '#/components/schemas/TokenInfo'
        total:
          oneOf:
          - $ref: '#/components/schemas/TotalERC20'
          - $ref: '#/components/schemas/TotalERC721'
          - $ref: '#/components/schemas/TotalERC1155'
        transaction_hash:
          type: string
          example: '0x6662ad1ad2ea899e9e27832dc202fd2ef915a5d2816c1142e6933cff93f7c592'
        type:
          type: string
          example: token_transfer
    WatchlistName:
      type: object
      required:
      - display_name
      - label
      properties:
        display_name:
          type: string
          example: name to show
        label:
          type: string
          example: label
    RawTrace:
      type: object
      required:
      - action
      - subtraces
      - traceAddress
      - type
      properties:
        action:
          oneOf:
          - $ref: '#/components/schemas/RawTraceCallAction'
          - $ref: '#/components/schemas/RawTraceCreateAction'
          - $ref: '#/components/schemas/RawTraceSelfDestructAction'
        subtraces:
          type: integer
          example: 0
        traceAddress:
          type: array
          items:
            type: integer
          example:
          - 0
          - 0
        type:
          type: string
          example: call
        error:
          type: string
          example: Reverted
        result:
          oneOf:
          - $ref: '#/components/schemas/RawTraceCallResult'
          - $ref: '#/components/schemas/RawTraceCreateResult'
    TokenInfo:
      type: object
      required:
      - address
      - circulating_market_cap
      - icon_url
      - symbol
      - name
      - decimals
      - type
      - holders
      - exchange_rate
      - total_supply
      properties:
        circulating_market_cap:
          type: string
          example: '83606435600.3635'
        icon_url:
          type: string
          example: https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png
        name:
          type: string
          example: Tether USD
        decimals:
          type: string
          example: '6'
        symbol:
          type: string
          example: USDT
        address_hash:
          type: string
          example: '0x394c399dbA25B99Ab7708EdB505d755B3aa29997'
        type:
          type: string
          example: ERC-20
        holders_count:
          type: string
          example: '837494234523'
        exchange_rate:
          type: string
          example: '0.99'
        total_supply:
          type: string
          example: '10000000'
    TransactionActionAaveV3EnableDisableCollateral:
      required:
      - data
      - protocol
      - type
      properties:
        data:
          type: object
          example:
            symbol: AAVE
            address: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9'
            block_number: 1
        protocol:
          type: string
          example: aave_v3
        type:
          type: string
          example: enable_collateral | disable_collateral
    TransactionAction:
      oneOf:
      - $ref: '#/components/schemas/TransactionActionAaveV3LiquidationCall'
      - $ref: '#/components/schemas/TransactionActionAaveV3BSWRF'
      - $ref: '#/components/schemas/TransactionActionAaveV3EnableDisableCollateral'
      - $ref: '#/components/schemas/TransactionActionUniswapV3MintNFT'
      - $ref: '#/components/schemas/TransactionActionUniswapV3BCS'
    ERC20Or1155OrCoinChange:
      type: string
      example: '-10000000'
    SummaryTemplateVariables:
      type: object
      required:
      - action_type
      - amount
      - token
      properties:
        action_type:
          $ref: '#/components/schemas/SummaryVariable'
          description: Action type
        amount:
          $ref: '#/components/schemas/SummaryVariableCurrency'
          description: Amount
        token:
          $ref: '#/components/schemas/SummaryVariableToken'
          description: Token info
    TotalERC721:
      required:
      - token_id
      properties:
        token_id:
          type: string
          example: '1'
        token_instance:
          $ref: '#/components/schemas/NFTInstance'
    SummaryVariableToken:
      type: object
      required:
      - type
      - value
      properties:
        type:
          type: string
          example: token
          description: Type
        value:
          $ref: '#/components/schemas/TokenInfoDetailed'
          description: Token info
    TransactionSummaryObj:
      type: object
      properties:
        summaries:
          type: array
          items:
            $ref: '#/components/schemas/Summary'
    TransactionActionAaveV3LiquidationCall:
      required:
      - data
      - protocol
      - type
      properties:
        data:
          type: object
          example:
            debt_amount: '1.289548595490270429'
            debt_symbol: AAVE
            debt_address: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9'
            collateral_amount: '110.824768'
            collateral_symbol: USDC
            collateral_address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48'
            block_number: 1
        protocol:
          type: string
          example: aave_v3
        type:
          type: string
          example: liquidation_call
    Fee:
      type: object
      required:
      - type
      - value
      properties:
        type:
          type: string
          example: maximum | actual
        value:
          type: string
          example: '9853224000000000'
    NFTChangesArray:
      type: array
      items:
        $ref: '#/components/schemas/NFTChange'
    SummaryVariable:
      type: object
      required:
      - type
      - value
      properties:
        type:
          type: string
          example: string
          description: Variable type
        value:
          type: string
          example: Registered withdrawal of
          description: Action Type
    TransactionActionUniswapV3BCS:
      required:
      - data
      - protocol
      - type
      properties:
        data:
          type: object
          example:
            address0: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9'
            address1: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48'
            amount0: '1.289548595490270429'
            amount1: '110.824768'
            symbol0: AAVE
            symbol1: USDC
        protocol:
          type: string
          example: uniswap_v3
        type:
          type: string
          example: burn | collect | swap
    AddressTag:
      type: object
      required:
      - address_hash
      - display_name
      - label
      properties:
        address_hash:
          type: string
          example: '0xEb533ee5687044E622C69c58B1B12329F56eD9ad'
        display_name:
          type: string
          example: name to show
        label:
          type: string
          example: label
    DecodedInputLogParameter:
      type: object
      required:
      - name
      - type
      - value
      - indexed
      properties:
        name:
          type: string
          example: signature
        type:
          type: string
          example: bytes
        value:
          type: string
          example: '0x0'
        indexed:
          type: boolean
    DecodedInputParameter:
      type: object
      required:
      - name
      - type
      - value
      properties:
        name:
          type: string
          example: signature
        type:
          type: string
          example: bytes
        value:
          type: string
          example: '0x0'
    RawTraceCallAction:
      type: object
      required:
      - callType
      - to
      - from
      - input
      - gas
      - value
      properties:
        callType:
          type: string
          example: call
        to:
          type: string
          example: '0x162e898bd0aacb578c8d5f8d6ca588c13d2a383f'
        from:
          type: string
          example: '0xf57b55b01b831e602e09674a4e5d69cbcf343f98'
        input:
          type: string
          example: '0x630cea8e000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000041c25b36779231e71769118210c3eb64c0a9c7577b925b309af3183e13acc7cf30210493d13c8c6c3c0bd337d5e39e454fece0c301f0aedb6c43c7a37650ac83e71c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000019500050000f0add9e5dc02faeca12e9669f045685449d6b80a000000000000744359447362798334d3485c64d1e4870fde2ddc0d75f0b456250dc9990662a6f25808cc74a6d1131ea9000927c001018064382ae87cdd000000000000000000000000bab3cbdcbcc578445480a79ed80269c50bb5b71800000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000012000000000000000000000000351af1631aa5ea1ca62ad8a4e3cd87128d4d910800000000000000000000000000000000000000000000005b8decde02914ce837000000000000000000000000000000000000000000000000000000000000001e4d45444f4f5a412045636f73797374656d2076322e30206f6e2078446169000000000000000000000000000000000000000000000000000000000000000000044d445a41000000000000000000000000000000000000000000000000000000000000000000000000000000'
        gas:
          type: string
          example: '0x25D3FC'
        value:
          type: string
          example: '0x0'
    NFTInstance:
      required:
      - is_unique
      - id
      - token
      - owner
      properties:
        is_unique:
          type: boolean
        id:
          type: string
          example: '431'
        holder_address_hash:
          type: string
          example: '0x394c399dbA25B99Ab7708EdB505d755B3aa29997'
        image_url:
          type: string
          example: example.com/picture.png
        animation_url:
          type: string
          example: example.com/video.mp4
        external_app_url:
          type: string
          example: d-app.com
        metadata:
          type: object
          example:
            year: 2023
            tags:
            - poap
            - event
            name: 'Social Listening Committee #2 Attendees'
            image_url: https://assets.poap.xyz/chanel-poap-4c-2023-logo-1675083420470.png
            home_url: https://app.poap.xyz/token/6292128
            external_url: https://api.poap.tech/metadata/99010/6292128
            description: This is the POAP for attendees of the second Social Listening Committee.
            attributes:
            - value: 01-Feb-2023
              trait_type: startDate
            - value: 01-Feb-2023
              trait_type: endDate
            - value: 'false'
              trait_type: virtualEvent
            - value: Paris
              trait_type: city
            - value: France
              trait_type: country
            - value: https://www.chanel.com
              trait_type: eventURL
        owner:
          $ref: '#/components/schemas/AddressParam'
        token:
          $ref: '#/components/schemas/TokenInfo'
    RawTraceCallResult:
      type: object
      required:
      - gasUsed
      - output
      properties:
        gasUsed:
          type: string
          example: '0x25D3FC'
        output:
          type: string
          example: '0x0'
    AddressParam:
      type: object
      required:
      - hash
      - implementation_name
      - is_contract
      - is_verified
      - name
      - private_tags
      - public_tags
      - watchlist_names
      properties:
        hash:
          type: string
          example: '0xEb533ee5687044E622C69c58B1B12329F56eD9ad'
        implementation_name:
          type: string
          example: implementationName
        name:
          type: string
          example: contractName
        ens_domain_name:
          type: string
          example: domain.eth
        metadata:
          type: object
          example:
            slug: tag_slug
            name: Tag name
            tagType: name
            ordinal: 0
            meta: {}
        is_contract:
          type: boolean
        private_tags:
          type: array
          items:
            $ref: '#/components/schemas/AddressTag'
        watchlist_names:
          type: array
          items:
            $ref: '#/components/schemas/WatchlistName'
        public_tags:
          type: array
          items:
            $ref: '#/components/schemas/AddressTag'
        is_verified:
          type: boolean
    StateChange:
      required:
      - address
      - is_miner
      - type
      properties:
        token:
          $ref: '#/components/schemas/TokenInfo'
        type:
          type: string
          example: coin | token
        is_miner:
          type: boolean
        address_hash:
          $ref: '#/components/schemas/AddressParam'
        balance_before:
          type: string
          example: '100000000'
        balance_after:
          type: string
          example: '100000000'
        token_id:
          type: string
          example: null
        change:
          oneOf:
          - $ref: '#/components/schemas/NFTChangesArray'
          - $ref: '#/components/schemas/ERC20Or1155OrCoinChange'
    Log:
      type: object
      required:
      - address
      - data
      - decoded
      - index
      - smart_contract
      - topics
      - transaction_hash
      properties:
        address_hash:
          $ref: '#/components/schemas/AddressParam'
        block_hash:
          type: string
          example: '0xf90fdff5f174f7f29ebdf203d32cad2fe95376e41880bb9e731ca5eb0eef7941'
        block_number:
          type: integer
          example: 8844586
        data:
          type: string
          example: '0x000000000000000000000000000000000000000000000000006a94d74f430000'
        decoded:
          $ref: '#/components/schemas/DecodedInputLog'
          example:
            method_call: Transfer(address indexed from, address indexed to, uint256 tokens)
            method_id: '0x630cea8e'
            parameters:
            - name: signature
              type: bytes
              indexed?: true
              value: '0x0'
            - name: message
              type: bytes
              indexed?: false
              value: '0x01'
        index:
          type: integer
          example: 35
        smart_contract:
          $ref: '#/components/schemas/AddressParam'
        topics:
          type: array
          items:
            type: string
            example: '0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c'
        transaction_hash:
          type: string
          example: '0x08ea4d75ad0abe327a7fd368733eaeac43077989e635d800530d7906ebf3bd54'
  parameters:
    transactionHash:
      name: transaction_hash
      in: path
      description: Transaction hash
      required: true
      schema:
        type: string
        pattern: ^0x([A-Fa-f0-9]{64})$
