openapi: 3.0.0
info:
  description: API for BlockScout web app
  version: 1.0.0
  title: BlockScout Addresses API
  contact:
    email: support@blockscout.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://eth.blockscout.com/api/v2/
  description: Ethereum mainnet
- url: https://optimism.blockscout.com/api/v2/
  description: Optimism mainnet
- url: https://base.blockscout.com/api/v2/
  description: Base mainnet
- url: https://eth-sepolia.blockscout.com/api/v2/
  description: Ethereum testnet
tags:
- name: Addresses
paths:
  /addresses:
    get:
      summary: get native coin holders list
      operationId: get_addresses
      responses:
        '200':
          description: token
          content:
            application/json:
              schema:
                type: object
                required:
                - exchange_rate
                - total_supply
                - items
                - next_page_params
                properties:
                  exchange_rate:
                    type: string
                    example: '0.01'
                  total_supply:
                    type: string
                    example: '100000000'
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/AddressWithTxCount'
                  next_page_params:
                    type: object
                    example:
                      fetched_coin_balance: '269536604956070000000'
                      hash: '0xf74769d9ffe1cd17f20b283995cf9e7fa2a262ed'
                      items_count: 50
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}:
    get:
      summary: get address info
      operationId: get_address
      parameters:
      - $ref: '#/components/parameters/addressHash'
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/counters:
    get:
      summary: get address counters
      operationId: get_address_counters
      parameters:
      - $ref: '#/components/parameters/addressHash'
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressCounters'
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/transactions:
    get:
      summary: get address transactions
      operationId: get_address_txs
      parameters:
      - $ref: '#/components/parameters/addressHash'
      - in: query
        name: filter
        schema:
          type: string
          example: to | from
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  next_page_params:
                    type: object
                    example:
                      block_number: 27736955
                      index: 4
                      items_count: 50
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/token-transfers:
    get:
      summary: get address token transfers
      operationId: get_address_token_transfers
      parameters:
      - $ref: '#/components/parameters/addressHash'
      - in: query
        name: type
        schema:
          type: string
          example: ERC-20,ERC-721,ERC-1155
      - in: query
        name: filter
        schema:
          type: string
          example: to | from
      - in: query
        name: token
        schema:
          type: string
          example: '0xb81afe27c103bcd42f4026cf719af6d802928765'
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/TokenTransfer'
                  next_page_params:
                    type: object
                    example:
                      block_number: 27736955
                      index: 4
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/internal-transactions:
    get:
      summary: get address internal transactions
      operationId: get_address_internal_txs
      parameters:
      - $ref: '#/components/parameters/addressHash'
      - in: query
        name: filter
        schema:
          type: string
          example: to | from
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/InternalTransaction'
                  next_page_params:
                    type: object
                    example:
                      block_number: 27625575
                      index: 0
                      items_count: 50
                      transaction_index: 0
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/logs:
    get:
      summary: get address logs
      operationId: get_address_logs
      parameters:
      - $ref: '#/components/parameters/addressHash'
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Log'
                  next_page_params:
                    type: object
                    example:
                      block_number: 27736955
                      index: 68
                      items_count: 50
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/blocks-validated:
    get:
      summary: get blocks validated by address
      operationId: get_address_blocks_validated
      parameters:
      - $ref: '#/components/parameters/addressHash'
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Block'
                  next_page_params:
                    type: object
                    example:
                      block_number: 27736955
                      items_count: 50
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/token-balances:
    get:
      summary: get all tokens balances for the address
      operationId: get_address_token_balances
      parameters:
      - $ref: '#/components/parameters/addressHash'
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TokenBalance'
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/tokens:
    get:
      summary: token balances with filtering and pagination
      operationId: get_address_tokens
      parameters:
      - $ref: '#/components/parameters/addressHash'
      - in: query
        name: type
        schema:
          type: string
          example: ERC-20,ERC-721,ERC-1155
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/TokenBalance'
                  next_page_params:
                    type: object
                    example:
                      items_count: 50
                      token_name: null
                      token_type: ERC-1155
                      value: 14
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/coin-balance-history:
    get:
      summary: get address coin balance history
      operationId: get_address_coin_balance_history
      parameters:
      - $ref: '#/components/parameters/addressHash'
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/CoinBalanceHistoryEntry'
                  next_page_params:
                    type: object
                    example:
                      block_number: 27736955
                      items_count: 50
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/coin-balance-history-by-day:
    get:
      summary: get address coin balance history by day
      operationId: get_address_coin_balance_history_by_day
      parameters:
      - $ref: '#/components/parameters/addressHash'
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CoinBalanceHistoryByDaysEntry'
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/withdrawals:
    get:
      summary: get address withdrawals
      operationId: get_address_withdrawals
      parameters:
      - $ref: '#/components/parameters/addressHash'
      responses:
        '200':
          description: pay attention that receiver field is not included to response in this endpoint
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Withdrawal'
                  next_page_params:
                    type: object
                    example:
                      index: 1
                      items_count: 50
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/nft:
    get:
      summary: get list of NFT owned by address
      operationId: get_address_nft
      parameters:
      - $ref: '#/components/parameters/addressHash'
      - in: query
        name: type
        schema:
          type: string
          example: ERC-721,ERC-404,ERC-1155
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/AddressNFTInstance'
                  next_page_params:
                    type: object
                    example:
                      token_contract_address_hash: '0xb81afe27c103bcd42f4026cf719af6d802928765'
                      token_id: '1011'
                      token_type: ERC-721
        '400':
          description: bad input parameter
      tags:
      - Addresses
  /addresses/{address_hash}/nft/collections:
    get:
      summary: get list of NFT owned by address, grouped by collection
      operationId: get_address_nft_collections
      parameters:
      - $ref: '#/components/parameters/addressHash'
      - in: query
        name: type
        schema:
          type: string
          example: ERC-721,ERC-404,ERC-1155
      responses:
        '200':
          description: address
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                - next_page_params
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/AddressNFTCollection'
                  next_page_params:
                    type: object
                    example:
                      token_contract_address_hash: '0xb81afe27c103bcd42f4026cf719af6d802928765'
                      token_type: ERC-721
        '400':
          description: bad input parameter
      tags:
      - Addresses
components:
  schemas:
    TotalERC20:
      required:
      - decimals
      - value
      properties:
        decimals:
          type: string
          example: '18'
        value:
          type: string
          example: '1000'
    DecodedInput:
      type: object
      required:
      - method_call
      - method_id
      - parameters
      properties:
        method_call:
          type: string
          example: transferFrom(address _from, address _to, uint256 _value)
        method_id:
          type: string
          example: 23b872dd
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/DecodedInputParameter'
    Address:
      type: object
      required:
      - hash
      properties:
        creator_address_hash:
          type: string
          example: '0xEb533ee5687044E622C69c58B1B12329F56eD9ad'
        creation_transaction_hash:
          type: string
          example: '0x1f610ff9c1efad6b5a8bb6afcc0786cd7343f03f9a61e2544fcff908cedee924'
        token:
          $ref: '#/components/schemas/TokenInfo'
        coin_balance:
          type: string
          example: '10000000'
        exchange_rate:
          type: string
          example: '1.01'
        implementation_address:
          type: string
          example: '0xEb533ee5687044E622C69c58B1B12329F56eD9ad'
        block_number_balance_updated_at:
          type: integer
          example: 27656552
        hash:
          type: string
          example: '0xEb533ee5687044E622C69c58B1B12329F56eD9ad'
        implementation_name:
          type: string
          example: implementationName
        name:
          type: string
          example: contractName
        is_contract:
          type: boolean
        private_tags:
          type: array
          items:
            $ref: '#/components/schemas/AddressTag'
        watchlist_names:
          type: array
          items:
            $ref: '#/components/schemas/WatchlistName'
        public_tags:
          type: array
          items:
            $ref: '#/components/schemas/AddressTag'
        is_verified:
          type: boolean
        has_beacon_chain_withdrawals:
          type: boolean
        has_logs:
          type: boolean
        has_token_transfers:
          type: boolean
        has_tokens:
          type: boolean
        has_validated_blocks:
          type: boolean
        creation_status:
          type: string
          example: selfdestructed | failed | success
    TokenBalance:
      type: object
      required:
      - value
      - token
      - token_id
      properties:
        token_instance:
          $ref: '#/components/schemas/NFTInstance'
        value:
          type: string
          example: '10000'
        token_id:
          type: string
          example: '123'
        token:
          $ref: '#/components/schemas/Token'
    DecodedInputLog:
      type: object
      required:
      - method_call
      - method_id
      - parameters
      properties:
        method_call:
          type: string
          example: transferFrom(address _from, address _to, uint256 _value)
        method_id:
          type: string
          example: 23b872dd
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/DecodedInputLogParameter'
    Transaction:
      type: object
      required:
      - timestamp
      - fee
      - gas_limit
      - block_number
      - status
      - method
      - confirmations
      - type
      - exchange_rate
      - to
      - transaction_burnt_fee
      - max_fee_per_gas
      - result
      - hash
      - gas_price
      - priority_fee
      - base_fee_per_gas
      - from
      - token_transfers
      - transaction_types
      - gas_used
      - created_contract
      - position
      - nonce
      - has_error_in_internal_transactions
      - actions
      - decoded_input
      - token_transfers_overflow
      - raw_input
      - value
      - max_priority_fee_per_gas
      - revert_reason
      - confirmation_duration
      - transaction_tag
      properties:
        timestamp:
          type: string
          example: '2022-08-02T07:18:05.000000Z'
        fee:
          $ref: '#/components/schemas/Fee'
        gas_limit:
          type: integer
        block_number:
          type: integer
          format: int32
          example: 23484035
        status:
          type: string
          example: ok | error
        method:
          type: string
          example: transferFrom
        confirmations:
          type: integer
          example: 1035
        type:
          type: integer
          example: 2
        exchange_rate:
          type: string
          example: '1866.51'
        to:
          nullable: true,
          $ref: '#/components/schemas/AddressParam'
        transaction_burnt_fee:
          type: string
          example: '1099596081903840'
        max_fee_per_gas:
          type: string
          example: '55357460102'
        result:
          type: string
          example: 'Error: (Awaiting internal transactions for reason)'
        hash:
          type: string
          example: '0x5d90a9da2b8da402b11bc92c8011ec8a62a2d59da5c7ac4ae0f73ec51bb73368'
        gas_price:
          type: string
          example: '26668595172'
        priority_fee:
          type: string
          example: '2056916056308'
        base_fee_per_gas:
          type: string
          example: '26618801760'
        from:
          $ref: '#/components/schemas/AddressParam'
        token_transfers:
          type: array
          items:
            $ref: '#/components/schemas/TokenTransfer'
        transaction_types:
          type: array
          items:
            type: string
          example:
          - token_transfer
          - contract_creation
          - contract_call
          - token_creation
          - coin_transfer
        gas_used:
          type: string
          example: '41309'
        created_contract:
          nullable: true,
          $ref: '#/components/schemas/AddressParam'
        position:
          type: integer
          example: 117
        nonce:
          type: integer
          example: 115
        has_error_in_internal_transactions:
          type: boolean
          example: false
        actions:
          type: array
          items:
            $ref: '#/components/schemas/TransactionAction'
        decoded_input:
          $ref: '#/components/schemas/DecodedInput'
        token_transfers_overflow:
          type: boolean
          example: false
        raw_input:
          type: string
          example: '0xa9059cbb000000000000000000000000ef8801eaf234ff82801821ffe2d78d60a0237f97000000000000000000000000000000000000000000000000000000003178cb80'
        value:
          type: string
          example: '0'
        max_priority_fee_per_gas:
          type: string
          example: '49793412'
        revert_reason:
          type: string
          example: 'Error: (Awaiting internal transactions for reason)'
        confirmation_duration:
          type: object
          example:
          - 0
          - 17479.0
        transaction_tag:
          type: string
          example: private_transaction_tag
    AddressWithTxCount:
      allOf:
      - $ref: '#/components/schemas/Address'
      - type: object
        required:
        - transactions_count
        properties:
          transactions_count:
            type: string
            example: '1234'
    AddressNFTInstanceCollection:
      required:
      - token_type
      - value
      - is_unique
      - id
      - owner
      properties:
        is_unique:
          type: boolean
        id:
          type: string
          example: '431'
        holder_address_hash:
          type: string
          example: '0x394c399dbA25B99Ab7708EdB505d755B3aa29997'
        image_url:
          type: string
          example: example.com/picture.png
        animation_url:
          type: string
          example: example.com/video.mp4
        external_app_url:
          type: string
          example: d-app.com
        metadata:
          type: object
          example:
            year: 2023
            tags:
            - poap
            - event
            name: 'Social Listening Committee #2 Attendees'
            image_url: https://assets.poap.xyz/chanel-poap-4c-2023-logo-1675083420470.png
            home_url: https://app.poap.xyz/token/6292128
            external_url: https://api.poap.tech/metadata/99010/6292128
            description: This is the POAP for attendees of the second Social Listening Committee.
            attributes:
            - value: 01-Feb-2023
              trait_type: startDate
            - value: 01-Feb-2023
              trait_type: endDate
            - value: 'false'
              trait_type: virtualEvent
            - value: Paris
              trait_type: city
            - value: France
              trait_type: country
            - value: https://www.chanel.com
              trait_type: eventURL
        owner:
          $ref: '#/components/schemas/AddressParam'
        token:
          type: object
          example: null
        token_type:
          type: string
          example: ERC-721
        value:
          type: string
          example: '1'
    TransactionActionUniswapV3MintNFT:
      required:
      - data
      - protocol
      - type
      properties:
        data:
          type: object
          example:
            name: 'Uniswap V3: Positions NFT'
            symbol: UNI-V3-POS
            address: '0x1F98431c8aD98523631AE4a59f267346ea31F984'
            to: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9'
            ids:
            - '1'
            - '2'
            block_number: 1
        protocol:
          type: string
          example: uniswap_v3
        type:
          type: string
          example: mint_nft
    InternalTransaction:
      type: object
      required:
      - block_number
      - created_contract
      - error
      - from
      - gas_limit
      - index
      - success
      - timestamp
      - to
      - transaction_hash
      - type
      - value
      properties:
        block_number:
          type: integer
          example: 8844586
        created_contract:
          $ref: '#/components/schemas/AddressParam'
        error:
          type: string
          example: reverted
        from:
          $ref: '#/components/schemas/AddressParam'
        gas_limit:
          type: string
          example: '351759'
        index:
          type: integer
          example: 1
        success:
          type: boolean
          example: true
        timestamp:
          type: string
          example: '2023-04-17T10:37:12.000000Z'
        to:
          $ref: '#/components/schemas/AddressParam'
        transaction_hash:
          type: string
          example: '0x08ea4d75ad0abe327a7fd368733eaeac43077989e635d800530d7906ebf3bd54'
        type:
          type: string
          example: call
        value:
          type: string
          example: '30000000000000000'
    AddressNFTInstance:
      required:
      - token_type
      - value
      - is_unique
      - id
      - token
      - owner
      properties:
        is_unique:
          type: boolean
        id:
          type: string
          example: '431'
        holder_address_hash:
          type: string
          example: '0x394c399dbA25B99Ab7708EdB505d755B3aa29997'
        image_url:
          type: string
          example: example.com/picture.png
        animation_url:
          type: string
          example: example.com/video.mp4
        external_app_url:
          type: string
          example: d-app.com
        metadata:
          type: object
          example:
            year: 2023
            tags:
            - poap
            - event
            name: 'Social Listening Committee #2 Attendees'
            image_url: https://assets.poap.xyz/chanel-poap-4c-2023-logo-1675083420470.png
            home_url: https://app.poap.xyz/token/6292128
            external_url: https://api.poap.tech/metadata/99010/6292128
            description: This is the POAP for attendees of the second Social Listening Committee.
            attributes:
            - value: 01-Feb-2023
              trait_type: startDate
            - value: 01-Feb-2023
              trait_type: endDate
            - value: 'false'
              trait_type: virtualEvent
            - value: Paris
              trait_type: city
            - value: France
              trait_type: country
            - value: https://www.chanel.com
              trait_type: eventURL
        owner:
          $ref: '#/components/schemas/AddressParam'
        token:
          $ref: '#/components/schemas/TokenInfo'
        token_type:
          type: string
          example: ERC-721
        value:
          type: string
          example: '1'
    Token:
      type: object
      required:
      - address
      - symbol
      - name
      - decimals
      - type
      - holders
      - exchange_rate
      - total_supply
      properties:
        name:
          type: string
          example: Tether USD
        decimals:
          type: string
          example: '16'
        symbol:
          type: string
          example: USDT
        address_hash:
          type: string
          example: '0x394c399dbA25B99Ab7708EdB505d755B3aa29997'
        type:
          type: string
          example: ERC-20
        holders_count:
          type: integer
          example: 837494234523
        exchange_rate:
          type: string
          example: '0.99'
        total_supply:
          type: string
          example: '10000000'
    TotalERC1155:
      required:
      - token_id
      - decimals
      - value
      properties:
        token_id:
          type: string
          example: '1'
        decimals:
          type: string
          example: null
        value:
          type: string
          example: '1000'
        token_instance:
          $ref: '#/components/schemas/NFTInstance'
    TransactionActionAaveV3BSWRF:
      required:
      - data
      - protocol
      - type
      properties:
        data:
          type: object
          example:
            amount: '1.289548595490270429'
            symbol: AAVE
            address: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9'
            block_number: 1
        protocol:
          type: string
          example: aave_v3
        type:
          type: string
          example: borrow | supply | withdraw | repay | flash_loan
    TokenTransfer:
      type: object
      required:
      - block_hash
      - from
      - log_index
      - to
      - token
      - total
      - transaction_hash
      - type
      properties:
        block_hash:
          type: string
          example: '0xf569ec751152b2f814001fc730f7797aa155e4bc3ba9cb6ba24bc2c8c9468c1a'
        from:
          $ref: '#/components/schemas/AddressParam'
        log_index:
          type: integer
          example: 16
        method:
          type: string
          example: transfer
        timestamp:
          type: string
          example: '2023-07-03T20:09:59.000000Z'
        to:
          $ref: '#/components/schemas/AddressParam'
        token:
          $ref: '#/components/schemas/TokenInfo'
        total:
          oneOf:
          - $ref: '#/components/schemas/TotalERC20'
          - $ref: '#/components/schemas/TotalERC721'
          - $ref: '#/components/schemas/TotalERC1155'
        transaction_hash:
          type: string
          example: '0x6662ad1ad2ea899e9e27832dc202fd2ef915a5d2816c1142e6933cff93f7c592'
        type:
          type: string
          example: token_transfer
    WatchlistName:
      type: object
      required:
      - display_name
      - label
      properties:
        display_name:
          type: string
          example: name to show
        label:
          type: string
          example: label
    TokenInfo:
      type: object
      required:
      - address
      - circulating_market_cap
      - icon_url
      - symbol
      - name
      - decimals
      - type
      - holders
      - exchange_rate
      - total_supply
      properties:
        circulating_market_cap:
          type: string
          example: '83606435600.3635'
        icon_url:
          type: string
          example: https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png
        name:
          type: string
          example: Tether USD
        decimals:
          type: string
          example: '6'
        symbol:
          type: string
          example: USDT
        address_hash:
          type: string
          example: '0x394c399dbA25B99Ab7708EdB505d755B3aa29997'
        type:
          type: string
          example: ERC-20
        holders_count:
          type: string
          example: '837494234523'
        exchange_rate:
          type: string
          example: '0.99'
        total_supply:
          type: string
          example: '10000000'
    TransactionActionAaveV3EnableDisableCollateral:
      required:
      - data
      - protocol
      - type
      properties:
        data:
          type: object
          example:
            symbol: AAVE
            address: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9'
            block_number: 1
        protocol:
          type: string
          example: aave_v3
        type:
          type: string
          example: enable_collateral | disable_collateral
    CoinBalanceHistoryEntry:
      type: object
      required:
      - block_number
      - block_timestamp
      - delta
      - value
      properties:
        transaction_hash:
          type: string
          example: '0x1f610ff9c1efad6b5a8bb6afcc0786cd7343f03f9a61e2544fcff908cedee924'
        block_number:
          type: integer
          example: 1584930
        block_timestamp:
          type: string
          example: '2022-08-02T07:18:05.000000Z'
        delta:
          type: string
          example: '-234959404'
        value:
          type: string
          example: '100232323'
    TransactionAction:
      oneOf:
      - $ref: '#/components/schemas/TransactionActionAaveV3LiquidationCall'
      - $ref: '#/components/schemas/TransactionActionAaveV3BSWRF'
      - $ref: '#/components/schemas/TransactionActionAaveV3EnableDisableCollateral'
      - $ref: '#/components/schemas/TransactionActionUniswapV3MintNFT'
      - $ref: '#/components/schemas/TransactionActionUniswapV3BCS'
    TotalERC721:
      required:
      - token_id
      properties:
        token_id:
          type: string
          example: '1'
        token_instance:
          $ref: '#/components/schemas/NFTInstance'
    Block:
      type: object
      required:
      - base_fee_per_gas
      - burnt_fees
      - burnt_fees_percentage
      - difficulty
      - extra_data
      - gas_limit
      - gas_target_percentage
      - gas_used
      - gas_used_percentage
      - hash
      - height
      - miner
      - nonce
      - parent_hash
      - priority_fee
      - rewards
      - size
      - state_root
      - timestamp
      - total_difficulty
      - transactions_count
      - transaction_fees
      - type
      - uncles_hashes
      - withdrawals_count
      properties:
        base_fee_per_gas:
          type: string
          example: '26618801760'
        burnt_fees:
          type: string
          example: '261263193229977120'
        burnt_fees_percentage:
          type: number
          example: 85.19028810863084
        difficulty:
          type: string
          example: '0'
        extra_data:
          type: string
          example: TODO
        gas_limit:
          type: string
          example: '30000000'
        gas_target_percentage:
          type: number
          example: -34.56675333333333
        gas_used:
          type: string
          example: '9814987'
        gas_used_percentage:
          type: number
          example: 32.71662333333333
        hash:
          type: string
          example: '0xf569ec751152b2f814001fc730f7797aa155e4bc3ba9cb6ba24bc2c8c9468c1a'
        height:
          type: integer
          example: 17615720
        miner:
          $ref: '#/components/schemas/AddressParam'
        nonce:
          type: string
          example: '0x0000000000000000'
        parent_hash:
          type: string
          example: '0xd464e02d81e2bdf6bc5fa9b8e33f0b564c464a82d821a3e56531f8636dc00dfa'
        priority_fee:
          type: string
          example: '45418705646601378'
        rewards:
          type: array
          items:
            $ref: '#/components/schemas/Reward'
        size:
          type: integer
          example: 49997
        state_root:
          type: string
          example: TODO
        timestamp:
          type: string
          example: '2023-07-03T20:09:59.000000Z'
        total_difficulty:
          type: string
          example: '58750003716598352816469'
        transactions_count:
          type: integer
          example: 120
        transaction_fees:
          type: string
          example: '306681898876578498'
        type:
          type: string
          example: block
        uncles_hashes:
          type: array
          items:
            type: string
            example: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347'
        withdrawals_count:
          type: integer
          example: 16
    AddressCounters:
      type: object
      required:
      - transactions_count
      - token_transfers_count
      - gas_usage_count
      - validations_count
      properties:
        transactions_count:
          type: string
          example: '0'
        token_transfers_count:
          type: string
          example: '0'
        gas_usage_count:
          type: string
          example: '0'
        validations_count:
          type: string
          example: '0'
    TransactionActionAaveV3LiquidationCall:
      required:
      - data
      - protocol
      - type
      properties:
        data:
          type: object
          example:
            debt_amount: '1.289548595490270429'
            debt_symbol: AAVE
            debt_address: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9'
            collateral_amount: '110.824768'
            collateral_symbol: USDC
            collateral_address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48'
            block_number: 1
        protocol:
          type: string
          example: aave_v3
        type:
          type: string
          example: liquidation_call
    CoinBalanceHistoryByDaysEntry:
      type: object
      required:
      - date
      - value
      properties:
        date:
          type: string
          example: '2022-08-02'
        value:
          type: number
          example: '100232323'
    Fee:
      type: object
      required:
      - type
      - value
      properties:
        type:
          type: string
          example: maximum | actual
        value:
          type: string
          example: '9853224000000000'
    Withdrawal:
      required:
      - index
      - amount
      - validator_index
      properties:
        index:
          type: integer
          example: 1
        amount:
          type: string
          example: '1000000000000000000'
        validator_index:
          type: integer
          example: 1
        receiver:
          $ref: '#/components/schemas/AddressParam'
        block_number:
          type: integer
          example: 1
        timestamp:
          type: string
          example: '2023-06-20T07:55:00.000000Z'
    TransactionActionUniswapV3BCS:
      required:
      - data
      - protocol
      - type
      properties:
        data:
          type: object
          example:
            address0: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9'
            address1: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48'
            amount0: '1.289548595490270429'
            amount1: '110.824768'
            symbol0: AAVE
            symbol1: USDC
        protocol:
          type: string
          example: uniswap_v3
        type:
          type: string
          example: burn | collect | swap
    AddressTag:
      type: object
      required:
      - address_hash
      - display_name
      - label
      properties:
        address_hash:
          type: string
          example: '0xEb533ee5687044E622C69c58B1B12329F56eD9ad'
        display_name:
          type: string
          example: name to show
        label:
          type: string
          example: label
    DecodedInputLogParameter:
      type: object
      required:
      - name
      - type
      - value
      - indexed
      properties:
        name:
          type: string
          example: signature
        type:
          type: string
          example: bytes
        value:
          type: string
          example: '0x0'
        indexed:
          type: boolean
    AddressNFTCollection:
      required:
      - token
      - token_instances
      properties:
        token:
          $ref: '#/components/schemas/TokenInfo'
        amount:
          type: string
          example: '1'
        token_instances:
          type: array
          items:
            $ref: '#/components/schemas/AddressNFTInstanceCollection'
    DecodedInputParameter:
      type: object
      required:
      - name
      - type
      - value
      properties:
        name:
          type: string
          example: signature
        type:
          type: string
          example: bytes
        value:
          type: string
          example: '0x0'
    NFTInstance:
      required:
      - is_unique
      - id
      - token
      - owner
      properties:
        is_unique:
          type: boolean
        id:
          type: string
          example: '431'
        holder_address_hash:
          type: string
          example: '0x394c399dbA25B99Ab7708EdB505d755B3aa29997'
        image_url:
          type: string
          example: example.com/picture.png
        animation_url:
          type: string
          example: example.com/video.mp4
        external_app_url:
          type: string
          example: d-app.com
        metadata:
          type: object
          example:
            year: 2023
            tags:
            - poap
            - event
            name: 'Social Listening Committee #2 Attendees'
            image_url: https://assets.poap.xyz/chanel-poap-4c-2023-logo-1675083420470.png
            home_url: https://app.poap.xyz/token/6292128
            external_url: https://api.poap.tech/metadata/99010/6292128
            description: This is the POAP for attendees of the second Social Listening Committee.
            attributes:
            - value: 01-Feb-2023
              trait_type: startDate
            - value: 01-Feb-2023
              trait_type: endDate
            - value: 'false'
              trait_type: virtualEvent
            - value: Paris
              trait_type: city
            - value: France
              trait_type: country
            - value: https://www.chanel.com
              trait_type: eventURL
        owner:
          $ref: '#/components/schemas/AddressParam'
        token:
          $ref: '#/components/schemas/TokenInfo'
    AddressParam:
      type: object
      required:
      - hash
      - implementation_name
      - is_contract
      - is_verified
      - name
      - private_tags
      - public_tags
      - watchlist_names
      properties:
        hash:
          type: string
          example: '0xEb533ee5687044E622C69c58B1B12329F56eD9ad'
        implementation_name:
          type: string
          example: implementationName
        name:
          type: string
          example: contractName
        ens_domain_name:
          type: string
          example: domain.eth
        metadata:
          type: object
          example:
            slug: tag_slug
            name: Tag name
            tagType: name
            ordinal: 0
            meta: {}
        is_contract:
          type: boolean
        private_tags:
          type: array
          items:
            $ref: '#/components/schemas/AddressTag'
        watchlist_names:
          type: array
          items:
            $ref: '#/components/schemas/WatchlistName'
        public_tags:
          type: array
          items:
            $ref: '#/components/schemas/AddressTag'
        is_verified:
          type: boolean
    Reward:
      type: object
      required:
      - reward
      - type
      properties:
        reward:
          type: integer
        type:
          type: string
          example: Miner Reward | Emission Reward | Chore Reward | Uncle Reward
    Log:
      type: object
      required:
      - address
      - data
      - decoded
      - index
      - smart_contract
      - topics
      - transaction_hash
      properties:
        address_hash:
          $ref: '#/components/schemas/AddressParam'
        block_hash:
          type: string
          example: '0xf90fdff5f174f7f29ebdf203d32cad2fe95376e41880bb9e731ca5eb0eef7941'
        block_number:
          type: integer
          example: 8844586
        data:
          type: string
          example: '0x000000000000000000000000000000000000000000000000006a94d74f430000'
        decoded:
          $ref: '#/components/schemas/DecodedInputLog'
          example:
            method_call: Transfer(address indexed from, address indexed to, uint256 tokens)
            method_id: '0x630cea8e'
            parameters:
            - name: signature
              type: bytes
              indexed?: true
              value: '0x0'
            - name: message
              type: bytes
              indexed?: false
              value: '0x01'
        index:
          type: integer
          example: 35
        smart_contract:
          $ref: '#/components/schemas/AddressParam'
        topics:
          type: array
          items:
            type: string
            example: '0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c'
        transaction_hash:
          type: string
          example: '0x08ea4d75ad0abe327a7fd368733eaeac43077989e635d800530d7906ebf3bd54'
  parameters:
    addressHash:
      name: address_hash
      in: path
      description: Address hash
      required: true
      schema:
        type: string
        pattern: ^0x([A-Fa-f0-9]{40})$
